from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from datetime import datetime

def create_legal_notice(violations: list, output_filename: str):
    """
    Generates a formal PDF Legal Notice with auto-wrapping text.
    """
    doc = SimpleDocTemplate(
        output_filename,
        pagesize=letter,
        rightMargin=72, leftMargin=72,
        topMargin=72, bottomMargin=18
    )

    styles = getSampleStyleSheet()
    story = []

    # --- 1. HEADER ---
    title_style = styles['Title']
    story.append(Paragraph("FORMAL NOTICE: DEFECTIVE RENTAL AGREEMENT", title_style))
    story.append(Spacer(1, 12))

    # --- 2. DATE ---
    date_str = datetime.now().strftime("%d %B, %Y")
    align_right = ParagraphStyle(name='RightAlign', parent=styles['Normal'], alignment=2)
    story.append(Paragraph(f"<b>Date:</b> {date_str}", align_right))
    story.append(Spacer(1, 24))

    # --- 3. INTRO ---
    story.append(Paragraph("To the Landlord / Property Manager,", styles['Normal']))
    story.append(Spacer(1, 12))
    
    intro_text = """
    I have reviewed the proposed rental agreement. Upon legal audit, 
    the following clauses were found to be in violation of the 
    <b>Maharashtra Rent Control Act (1999)</b> / <b>Indian Contract Act</b>.
    """
    story.append(Paragraph(intro_text, styles['Normal']))
    story.append(Spacer(1, 24))
    
    story.append(Paragraph("<b>LIST OF VIOLATIONS:</b>", styles['Heading3']))
    story.append(Spacer(1, 12))

    # --- 4. DYNAMIC VIOLATIONS LOOP ---
    # Create a custom red style for violations
    red_style = ParagraphStyle('RedViolation', parent=styles['Normal'], textColor=colors.red)

    for i, v in enumerate(violations, 1):
        # CLAUSE (Wrapped automatically)
        clause_text = f"<b>{i}. CLAUSE:</b> {v.get('violated_clause_text', 'N/A')}"
        story.append(Paragraph(clause_text, styles['Normal']))
        
        # VIOLATION (Red & Wrapped)
        law_text = f"<b>VIOLATION:</b> {v.get('relevant_law_section', 'Unknown Section')}"
        story.append(Paragraph(law_text, red_style))
        
        # REMEDY (Italic & Wrapped)
        remedy_text = f"<i>REQUIRED REMEDY: {v.get('suggested_remedy', 'Remove clause')}</i>"
        story.append(Paragraph(remedy_text, styles['Normal']))
        
        # Space between items
        story.append(Spacer(1, 18))

    # --- 5. FOOTER ---
    story.append(Spacer(1, 36))
    footer_text = "This document was automatically generated by <b>Bureaucracy Bulldozer</b>."
    story.append(Paragraph(footer_text, styles['Italic']))

    # Build the PDF
    doc.build(story)
    return output_filename